package jp.keio.k_sawada.spring_db_learn.share.nature

enum class Nature(correction: Correction) {
    さみしがり(Correction(up = Stats.A, down = Stats.B)),
    いじっぱり(Correction(up = Stats.A, down = Stats.C)),
    やんちゃ(Correction(up = Stats.A, down = Stats.D)),
    ゆうかん(Correction(up = Stats.A, down = Stats.S)),
    ずぶとい(Correction(up = Stats.B, down = Stats.A)),
    わんぱく(Correction(up = Stats.B, down = Stats.C)),
    のうてんき(Correction(up = Stats.B, down = Stats.D)),
    のんき(Correction(up = Stats.B, down = Stats.S)),
    ひかえめ(Correction(up = Stats.C, down = Stats.A)),
    おっとり(Correction(up = Stats.C, down = Stats.B)),
    うっかりや(Correction(up = Stats.C, down = Stats.D)),
    れいせい(Correction(up = Stats.C, down = Stats.S)),
    おだやか(Correction(up = Stats.D, down = Stats.A)),
    おとなしい(Correction(up = Stats.D, down = Stats.B)),
    しんちょう(Correction(up = Stats.D, down = Stats.C)),
    なまいき(Correction(up = Stats.D, down = Stats.S)),
    おくびょう(Correction(up = Stats.S, down = Stats.A)),
    せっかち(Correction(up = Stats.S, down = Stats.B)),
    ようき(Correction(up = Stats.S, down = Stats.C)),
    むじゃき(Correction(up = Stats.N, down = Stats.N)),
    がんばりや(Correction(up = Stats.N, down = Stats.N)),
    すなお(Correction(up = Stats.N, down = Stats.N)),
    てれや(Correction(up = Stats.N, down = Stats.N)),
    まじめ(Correction(up = Stats.N, down = Stats.N)),
    きまぐれ(Correction(up = Stats.N, down = Stats.N)),
}